#!/bin/bash

battery() {
	BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`
	echo 100
}
battery_stat() {
	BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`
	echo 100
}

if [[ "$1" == "--bat" ]]; then
	battery
elif [[ "$1" == "--bat-st" ]]; then
	battery_stat
fi

