#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit twitter youtube weather apps mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--ff" ]]; then
	close_dash && firefox &

elif [[ "$1" == "--tb" ]]; then
	close_dash && thunderbird &

elif [[ "$1" == "--sl" ]]; then
	close_dash && slack &

elif [[ "$1" == "--tr" ]]; then
	close_dash && alacritty --working-directory ~ &

elif [[ "$1" == "--fm" ]]; then
	close_dash && thunar ~ &

elif [[ "$1" == "--cd" ]]; then
	close_dash && code &

elif [[ "$1" == "--pc" ]]; then
	close_dash && pycharm-professional &

elif [[ "$1" == "--cl" ]]; then
	close_dash && dex ~/.local/share/applications/claude-ai.desktop &

elif [[ "$1" == "--mo" ]]; then
	close_dash && dex ~/.local/share/applications/gtec-mondahy.desktop &

fi
