#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit twitter youtube weather apps mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--sh" ]]; then
	close_dash && systemctl shutdown

elif [[ "$1" == "--re" ]]; then
	close_dash && systemctl reboot

elif [[ "$1" == "--sl" ]]; then
	close_dash && qtile cmd-obj -o cmd -f shutdown

elif [[ "$1" == "--ex" ]]; then
	close_dash && qtile cmd-obj -o cmd -f shutdown
fi
