#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
CFG="$HOME/.config/eww/bar"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} --config "$CFG" daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} --config "$CFG" open-many \
         bar bar_top_monitor
}

## Create file needed to track state of bar
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
fi

# open bar
run_eww
